# Generated by Django 4.0.5 on 2022-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurieToCommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curie', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='GeneToPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_curie', models.CharField(max_length=35)),
                ('pathway_curie', models.CharField(max_length=35)),
                ('p_value', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayToGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_curie', models.CharField(max_length=35)),
                ('gene_curie', models.CharField(max_length=35)),
                ('p_value', models.CharField(max_length=35)),
            ],
        ),
    ]
