# Generated by Django 3.2.5 on 2021-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathwayLookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathwaytogene',
            name='id',
        ),
        migrations.AlterField(
            model_name='pathwaytogene',
            name='pathway',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
