# Generated by Django 3.2.5 on 2021-07-01 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathwayLookup', '0002_auto_20210701_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetopathway',
            name='gene',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genetopathway',
            name='pathways',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), size=None),
        ),
        migrations.AlterField(
            model_name='pathwaytogene',
            name='genes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), size=None),
        ),
        migrations.AlterField(
            model_name='pathwaytogene',
            name='pathway',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
    ]
